name = "openclaw-dashboard"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
PLATFORM = "cloudflare-workers"

[[kv_namespaces]]
binding = "DASHBOARD"
id = "603369472d324464bf0d47e0341bd462"

[env.production]
kv_namespaces = []
